spring.application.name=demo

# DB1 Configuration
spring.datasource.db1.jdbc-url=jdbc:mysql://localhost:3306/cache_project
spring.datasource.db1.username=root
spring.datasource.db1.password=Shaik@123
spring.datasource.db1.driver-class-name=com.mysql.cj.jdbc.Driver

# DB2 Configuration
spring.datasource.db2.jdbc-url=jdbc:mysql://localhost:3306/jobs_db
spring.datasource.db2.username=root
spring.datasource.db2.password=Shaik@123
spring.datasource.db2.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
